server:
  build: .
  dockerfile: /etc/docker/dockerfile_php_7
  volumes:
    - ./sites:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
#  ports:
#    - "80:80"
#    - "8080:8080"
  links:
    - db


db:
  image: bitnami/mariadb
#  ports:
#    - "3306:3306"
  environment:
    - MARIADB_ROOT_PASSWORD=23
    - MYSQL_DATABASE=DATABASE
  volumes:
#    - ./etc/mysql:/docker-entrypoint-initdb.d
#    - ./etc/mysql/db:/opt/bitnami/mariadb/data/
