server:
  build: .
  dockerfile: /etc/docker/debian-php-7.2/dockerfile
  volumes:
    - './sites:/var/www/html'
    - './etc/php/logs:/var/log/apache2'
    - './etc/php:/usr/local/etc/php'
    - './etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf'
    - './etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf'
    - './etc/apache2/httpd.conf:/etc/apache2/httpd.conf'
    - './etc/apache2/pid:/var/run/apache2.pid'
#    ports:
#      - '80'
#     - "80:80"
#     - "8080:8080"
  links:
    - mariadb

mariadb:
  image: 'bitnami/mariadb'
  ports:
    - '3306'
#     - '3306:3306'
  volumes:
    - './etc/mariadb:/bitnami'
    - './etc/mariadb:/docker-entrypoint-initdb.d'
    - './etc/mariadb/logs:/opt/bitnami/mariadb/logs'
  environment:
    - MARIADB_ROOT_PASSWORD=23
    - MARIADB_DATABASE=DATABASE
#     - ALLOW_EMPTY_PASSWORD=yes
    - MARIADB_USER=user
    - MARIADB_PASSWORD=ser
